### ISSUE TITLE
Lighthouse report

### ISSUE THREAD

**Issue by jos-b** [CyberDiscovery/cyberdiscovery.github.io#19]
Beano told me to put this here. I've compiled the results of lighthouse into a selection of bullet points.

# Performance
<img width="809" alt="image" src="https://user-images.githubusercontent.com/20439493/54499925-5facad80-490f-11e9-9948-5c00c8e0f33c.png">

# Load times

I have put the issue and next to it the amount of time that could be saved (estimate) by making the change, changes are ranked by speed increase.

## Optimisations

* Use WebP or JPEG 2000 over PNG/JPEG for improved compression rates and faster load times (8.85s)
* Properly size images, store in the repo at the size they will be displayed to remove unnecessary loading (3.9s)
* Defer offscreen images - lazy load images not displayed immediately (1.76s)
* Minify JavaScript (1.15s)
* Remove unused CSS (1.15s)
* Eliminate render blocking resources - some resources block the first paint of the page, deliver critical JS/CSS inline and defer all non-critical (1.12s)

## Issues

* Use the CSS `font-display` feature to ensure text is visible during webfont loading.
* Serve static assets with an efficient cache policy, 40 resources are being used with inefficient caching
* Minimise work done on the main thread, make user of JavaScript workers

# Best Practices
* Make touch and wheel event listeners `passive` to improve the scroll performance on the page
* Links to cross-origin destinations are unsafe, add `rel="noopener"` or `rel="noreferrer"` to any external links to improve performance and prevent security vulnerabilities
* Image display dimensions should match the natural aspect ratio

Note: These are all recommendations, time increases are estimates by the software. Some of these issues could be invalid/unfixable.

**Comment by Sh3llcod3** [comment]
@jos-b Thanks man, over the next week or so, I'll take these things into account and maybe we can work something out! :smile:

**Comment by jos-b** [comment]
Sounds good!

**Comment by thebeanogamer** [comment]
Additionally, whilst we're running automated tools, we should probably have a look at the Security Headers where we can at some point.
![image](https://user-images.githubusercontent.com/3729048/54519253-fe5ffb00-495d-11e9-9532-1e8590b1b1fd.png)

Results here: https://securityheaders.com/?q=cyberdiscoverycommunity.uk&followRedirects=on

Not sure how much of this GitHun Pages will let us do though.

**Comment by Sh3llcod3** [comment]
Ok, headers aside for a second, I plan to run all the images through imagemagick's `convert` binary on my Ubuntu 16.04.6 main site-dev box. This has historically produced some great results and using the Google PageSpeed recommended settings for convert, I have seen some amazing compression ratios. This hasn't always worked though and I've seen file sizes for images increase on several occasions. 

* I am not fulling willing to commit to permanently resizing them to a much small size as this would drastically reduce the quality of the images, which is why I'm assuming that websites store several versions of an asset? (Currently all if not most assets are targetted at 2k-4k in resolution)
* I am not sure if I should change all the images to webp either. I'm certain that will have a better compression ratio than bog-standard PNG or JPEG, but compatibility across browsers remains very limited as of yet. Adding a fall-back method to fall-back on traditional formats works here too but it requires quite a bit of JS hackery.

**Comment by jos-b** [comment]
I think that a valid solution for your first point would be storing the full-res assets in a folder called `assets` and maybe placing the resized images at the biggest size used across all pages in a `static` folder or whatever.

You raise a good point about the WebP support. I wonder if there could be a polyfill out there that we could use?

**Comment by jos-b** [comment]
This doesn't look too shabby: [webp-polyfill](https://github.com/FallingSnow/webp-polyfill)

We could just load in all the images as webp and run
```js
webpPolyfill.evaluateParent('body');
```

**Comment by Sh3llcod3** [comment]
This looks like something I need to look into :eyes:

**Comment by Sh3llcod3** [comment]
@jos-b What do you think about #22?

**Comment by joker314** [comment]
# Headers
I have compiled my thoughts on each header and how we should mitigate any reported issues by securityheaders.io. I have left summary values that I think we should include for the currently non-passing headers. These summaries are also collected here. This took a not short time to write when fully expanded :slightly_smiling_face:

- `X-Frame-Options` can either be safely ommitted or set to `ALLOWALL`;
- `Content-Security-Policy` should be set to something but after some further investigation, but initially the `Content-Security-Policy-Report-Only` can be used to test things out or a broad policy can be set;
- `Referrer-Policy` should be set to `no-referrer` if we don't want to do analytics or otherwise `strict-origin` if we do. If we don't really care too much we can set the value to something which requires HTTPS and I'd be okay with that


<details>
<summary><code>Strict-Transport-Security</code> and related security measures (<strong>Pass</strong> :heavy_check_mark: )</summary>

This header informs the client that, when making a request in the future, it should automatically use a secure `HTTPS` connection, preventing a Man-in-the-Middle (MitM) attack.

However, this does not prevent MitM attacks on the very first connection. For that, browsers need to be informed in advance. Our website is in Chrome's HSTS (<b>H</b>TTP <b>S</b>trict-<b>T</b>ransport-Security) list (which is used by multiple other browsers). This means users are forced by their clients to use HTTPS even on the very first time.

![The HSTS preload list confirms that our website is listed](https://user-images.githubusercontent.com/18113170/56048951-30902d00-5d51-11e9-904d-c4ed5d8db10f.png)


This is very good as we are stopping MitM attacks very well. Stopping these attacks is important because an attack can have the following impact:
- If our website content is replaced, a user may be phished if they trust our website more than that of others
- If our website content is replaced, a user may find the content disrespectful and we could be distrusted by that user
</details>

<details>
<summary><code>X-Content-Type-Options</code> and related security measures (<strong>Pass</strong> :heavy_check_mark: )</summary>

If we host user-generated content and it is maliciously crafted so as to look like a script or stylesheet, some browsers may ignore the `Content-Type` header and instead sniff the MIME type. Because the user-generated files are not meant to be executed in the context of the web page, this could lead to UI redressing or XSS.

However, we do not host user-generated content, so this does not apply to us. As a best practice, we currently are and should continue to set the header to `nosniff`
</details>

<details>
<summary><code>Content-Security-Policy</code> (<strong>Fail</strong> :x: )</summary>
<em>Proposed new value</em>: Depends on set-up but something like `default-src: self` and we must make sure to include any external images we are using. To test it out we can use the related header 
<hr>

The Content-Security-Policy defines where requests can originate from, and it has some of the features of the `X-Frame-Options` header and the like. Effectively, if we assume an XSS or HTML injection attack has already occured, this header can block some of the damage. This is especially true if we ban inline script tags or force them to have a one-time nonce attached thereto,

I don't think we can have an XSS attack with the current functionality that we possess: this is a static site. Nonetheless, it is important to defend against this. The CSP header can be introduced gradually and so a very short  value thereof may be better than nothing at all.

The CSP does not need to be fully enabled either, if you use the related header `Content-Security-Policy-Report-Only:` you can get console errors (and optionally some data sent to our server) about any violations so we can fix them before deploying the policy for real. 
</details>

<details>
<summary><code>X-Frame-Options</code> (<strong>Fail</strong> :x: )</summary>
<em>Proposed new value</em>: Either omit the header (and ignore the warning) or set it to the non-standard `ALLOWALL` which might make the warning go away. The threat that we are being warned about does not apply to us.
<hr>

Controls whether our site can be embeded. This has a negligable intellectual property angle that we don't need to think about, and then a security angle.

The security angle is that someone can perform an attack known as Clickjacking (UI Redressing). An attacker takes advantage of the idea that modern CSS allows for layering. If something (A) is on top of another thing (B), then when you click on the position of B, the click will go to A. This isn't a problem when A is covering up B, but consider the situation where the opacity of A is set to 0 such that it becomes transparent. Next, consider A is an iframe to the victim site's (allegedly us) content. Now imagine A's (our) site has a "Delete my account" button or another state-changing action. When the user clicks on B (which is underneath A and looks like a button or other enticing content), the click will go to the transparent element on top, A, and the user's account will be deleted.

But this does not apply to us! Because we do not have any state-changing buttons on our site because it is static.

Further, we *want* people to embed our site as it's a useful feature of the web. So we should explicitely state that in the header value `ALLOWALL` (non-standard) so that there is no warning.
</details>
<summary><code>X-XSS-Protection</code> (<strong>Fail</strong> :x: )</summary>
<em>Proposed new value</em>: `1; mode=block` (or maybe `0`)
<hr>

The options are `0`, which will not do any sanitising. That is sort of good to avoid false positives, but I don't think that's a big deal.

Or `1` which sanitises scripts. This is usually a bad idea as it can disable scripts that are vital to security.

Or `1; mode=block`
</details>

<details>
<summary><code>Referrer-Policy</code> (<strong>Fail</strong> :x: )</summary>
(Note correct spelling. Only time it's incorrect is for the standalone 'referer' header)
<em>Proposed new value</em>: `strict-origin` if we want to do analytics else `no-referrer`
<hr>

Effectively, when you navigate away from a page by clicking a link on it, data about where you just were are given to the new site.

Although the origin (i.e., domain name + port) must be shown, we should prevent the path from being seen. If we want to do analytics, then we can allow the referer to be shown on the same origin: `same-origin`, or, if we're obsessed with HTTPS (which we should be!) then `strict-origin`, which requires the link to have HTTPS.

If we don't want to do analytics, we can just disable `Referer` headers entirely with `no-referrer`.

If we trust all the sites we link to as long as they are HTTPS then we can use other headers which detect downgrades and the like.

Note images get referrer headers too!
</details>

<details>
<summary><code>Feature-Policy</code> (<strong>Fail</strong> :x: )</summary>
<em>Proposed new value</em>: `'none'`

Can the browser use the gyroscope? The microphone? The camera? We don't need to so let's opt-out. This is a really new header though.

If we ever do need to, we can opt in on a feature-by-feature basis. I do think it's unlikely someone will be able to hijack our ability to do any of those things though.
</details>

**Comment by Sh3llcod3** [comment]
@joker314 This is an excellent and ultra-detailed write-up, you must have put significant time and effort into this! :eyes: The thing about these header values is, since this is primarily hosted on GitHub pages, with some form of Cloud-flare reverse-proxy active, I don't know if I'll be able to directly control some of these header values, since header values are generally passed from the hosting web-server. If there is any JavaScript XHR trickery or header manipulation that I can do to resolve some of the issues, I will be happy to do so. I believe this is when @thebeanogamer comes in here, since he has the low-down on the back-end and consequently he might be able to manipulate some values here and there to resolve these issues. Let's see what can be done about them, you have raised some excellent points. 

Thanks for your feedback! :+1:

**Comment by joker314** [comment]
Some details, like Referer policies can be conveyed with meta tags.

These tags are mostly just best practices in our case. 

Nonetheless, moving to a host which provides more freedom sounds awesome!

**Comment by Sh3llcod3** [comment]
> Some details, like Referer policies can be conveyed with meta tags.
> These headers are mostly just best practices in our case.

Really? You mean I can set `<meta>` tags? I need to look this up.
Also yes, it is best practices, but good habits develop from best practices. :computer:

**Comment by Sh3llcod3** [comment]
Yeah, this definitely needs to remain open for a period of time until I can fix the load times.

**Comment by Sh3llcod3** [comment]
#23 has been created in order further address this issue.

**Comment by Sh3llcod3** [comment]
A rewrite is deep in the pipeline, can I release it on time is the question?

**Comment by Sh3llcod3** [comment]
A rewrite has been done to in an attempt to fix this issue, and `imgbot` has been employed to lossless compress images. If this persists or anyone is experiencing slow loads, I'll reopen this if referenced.
